### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by YasharSL** [ycw/three-lens-distortion#1]
Using three.js version 0.149.0 and above, I get this error for the `LensDistortionPassGen` function on it's initial use. I tried using the codes in the live example almost exactly and still got the same error. 
![image](https://github.com/ycw/three-lens-distortion/assets/80866837/12e2bff4-6441-4169-a23b-dd7e51701549)

I've written it in the Next.js v13 context. This is how I import the needed parts:
```
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import {
  EffectComposer,
  Pass,
  FullScreenQuad,
} from "three/examples/jsm/postprocessing/EffectComposer";
import { RenderPass } from "three/examples/jsm/postprocessing/RenderPass";
import { LensDistortionPassGen } from "three-lens-distortion";
import { Pane } from "tweakpane";
```

It might be an issue related to circular dependencies because I've seen this error pop up for this issue before but I cannot fully find out which part of the code is causing this so I don't really have any evidence to back up my guess.

**Comment by ycw** [comment]
my sample code seems outdated, sorry for that

since r148, the classes `Pass` and `FullScreenQuad` were only exported from 'postprocessing/Pass.js' module,

so please try:

```
import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
import { EffectComposer } from "three/examples/jsm/postprocessing/EffectComposer";
import { Pass, FullScreenQuad } from "three/examples/jsm/postprocessing/Pass";    // <<< here
import { RenderPass } from "three/examples/jsm/postprocessing/RenderPass";
import { LensDistortionPassGen } from "three-lens-distortion";
import { Pane } from "tweakpane";
```

:)

**Comment by YasharSL** [comment]
That's right. Thank you it works now. Mind if I make a pull request?
